# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20160517_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='fk_user',
            new_name='fk_user_created_by',
        ),
    ]
