# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20160526_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='fk_user',
            new_name='fk_user_created_by',
        ),
    ]
