# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20160527_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='fk_user',
            new_name='fk_user_created_by',
        ),
    ]
