# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20160527_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rank',
            name='is_attendee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rank',
            name='is_organiser',
            field=models.BooleanField(default=False),
        ),
    ]
