# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20160529_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issyncedwith',
            name='user_token',
        ),
        migrations.AddField(
            model_name='issyncedwith',
            name='user_id',
            field=models.CharField(default=None, max_length=2048),
            preserve_default=False,
        ),
    ]
